/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface BallotToElectionModel {
  a: string;
  b: string;
}
export interface CandidateUserModel {
  a: string;
  b: string;
}
export interface EventTrailModel {
  a: string;
  b: string;
}
export interface RunConditionModel {
  a: string;
  b: string;
}
export interface RunReporterModel {
  a: string;
  b: string;
}
export interface TrailRunReportModel {
  a: string;
  b: string;
}
export interface TrailVisitorModel {
  a: string;
  b: string;
}
export interface UserContactInfoModel {
  a: string;
  b: string;
}
export interface UserMetaModel {
  a: string;
  b: string;
}
export interface UserPreferencesModel {
  a: string;
  b: string;
}
export interface ActivityLogItemModel {
  createdAt?: Date | null;
  id: string;
  link?: string | null;
  message: string;
  messageCode: string;
  time: Date;
  updatedAt?: Date | null;
  user?: string | null;
}
export interface BallotModel {
  createdAt?: Date | null;
  desc?: string | null;
  id: string;
  title: string;
  updatedAt?: Date | null;
}
export interface BandaidModel {
  createdAt?: Date | null;
  description?: string | null;
  event?: string | null;
  id: string;
  memberInvolved?: string | null;
  title?: string | null;
  updatedAt?: Date | null;
}
export interface CloudinaryImageModel {
  createdAt?: Date | null;
  id: string;
  publicId: string;
  smallUrl?: string | null;
  updatedAt?: Date | null;
  url?: string | null;
}
export interface ConditionModel {
  createdAt?: Date | null;
  id: string;
  notes?: string | null;
  status: string;
  updatedAt?: Date | null;
}
export interface ContactInfoModel {
  city?: string | null;
  createdAt?: Date | null;
  id: string;
  phone?: string | null;
  state?: string | null;
  street?: string | null;
  updatedAt?: Date | null;
  zip?: string | null;
}
export interface ElectionModel {
  createdAt?: Date | null;
  electionName: string;
  endTime?: Date | null;
  id: string;
  startTime?: Date | null;
  updatedAt?: Date | null;
}
export interface EventModel {
  address?: string | null;
  changeDisabled?: any | null;
  createdAt?: Date | null;
  creator?: string | null;
  description?: string | null;
  endTime?: Date | null;
  featuredImage?: string | null;
  host?: string | null;
  id: string;
  maxAttendees?: number | null;
  maxRigs?: number | null;
  membersOnly?: any | null;
  rallyAddress?: string | null;
  startTime?: Date | null;
  title: string;
  trailDifficulty?: string | null;
  trailNotes?: string | null;
  type: string;
  updatedAt?: Date | null;
}
export interface MembershipLogItemModel {
  createdAt?: Date | null;
  id: string;
  logger?: string | null;
  message: string;
  messageCode: string;
  time?: Date | null;
  updatedAt?: Date | null;
  user?: string | null;
}
export interface PreferenceModel {
  createdAt?: Date | null;
  emergencyContactName?: string | null;
  emergencyContactPhone?: string | null;
  id: string;
  photoPermissions?: any | null;
  showPhoneNumber?: any | null;
  tshirtSize?: string | null;
  updatedAt?: Date | null;
}
export interface RegistrationModel {
  createdAt?: Date | null;
  email: string;
  firstName?: string | null;
  id: string;
  lastName?: string | null;
  source: string;
  token: string;
  tokenExpiry: Date;
  updatedAt?: Date | null;
}
export interface RigImageModel {
  id: string;
  image?: string | null;
}
export interface RsvpModel {
  createdAt?: Date | null;
  event?: string | null;
  guestCount?: number | null;
  id: string;
  isRider?: any | null;
  member?: string | null;
  status: string;
  updatedAt?: Date | null;
  vehicle?: string | null;
}
export interface RsvpEquipmentModel {
  nodeId: string;
  position: number;
  value: string;
}
export interface RunReportModel {
  createdAt?: Date | null;
  description?: string | null;
  difficulty: string;
  endTime?: Date | null;
  event?: string | null;
  favorite?: any | null;
  id: string;
  rating: number;
  reportFiled?: Date | null;
  startTime?: Date | null;
  title: string;
  updatedAt?: Date | null;
  weather: string;
}
export interface TrailModel {
  address?: string | null;
  createdAt?: Date | null;
  description?: string | null;
  featuredImage?: string | null;
  id: string;
  name?: string | null;
  slug: string;
  trailheadCoords?: string | null;
  updatedAt?: Date | null;
}
export interface UserModel {
  accountStatus: string;
  accountType: string;
  avatar?: string | null;
  birthdate?: Date | null;
  comfortLevel?: string | null;
  createdAt?: Date | null;
  email: string;
  firstName: string;
  gender?: string | null;
  id: string;
  joined?: Date | null;
  lastLogin?: Date | null;
  lastName: string;
  office?: string | null;
  password: string;
  resetToken?: string | null;
  resetTokenExpiry?: Date | null;
  rig?: string | null;
  role: string;
  updatedAt?: Date | null;
  username: string;
  vehicle?: string | null;
}
export interface UserEquipmentModel {
  nodeId: string;
  position: number;
  value: string;
}
export interface UserMetaModel {
  accountSetupComplete?: any | null;
  createdAt?: Date | null;
  emailMemberNotifications?: any | null;
  emailPublicNotifications?: any | null;
  emailVerified?: any | null;
  firstLoginComplete?: any | null;
  id: string;
  oldSiteMigrationComplete?: any | null;
  updatedAt?: Date | null;
}
export interface UserTitlesModel {
  nodeId: string;
  position: number;
  value: string;
}
export interface VehicleModel {
  createdAt?: Date | null;
  id: string;
  image?: string | null;
  make: string;
  model: string;
  name?: string | null;
  outfitLevel?: string | null;
  trim?: string | null;
  updatedAt?: Date | null;
  year: number;
}
export interface VehicleModsModel {
  nodeId: string;
  position: number;
  value: string;
}
export interface VoteModel {
  ballot?: string | null;
  candidate?: string | null;
  createdAt?: Date | null;
  id: string;
  updatedAt?: Date | null;
  voter?: string | null;
}
